### ISSUE TITLE
Adding a new line_in_file task

### ISSUE THREAD

**Issue by corentincharron** [cube-creative/jeanpaulstart#9]
Hello :)

I need to be able to add or remove a line in a text file. To do so, I'll create a new `line_in_file` that is a simplified (no regex) implementation of the [Ansible `lineinfile`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html).

This would be the design:

```
- name: Task Name
  line_in_file:
    src: /path/to/file.ext
    state: [present|absent]
    line: value
    insert_after: value
    insert_before: value
```

Any comment before I start working on it?
